// Assam — YojanaSetu State Schemes
// ─────────────────────────────────────────────────────────────────────────────
// HOW TO ADD A NEW SCHEME:
//   1. Copy any block below, paste it above the closing ];
//   2. Give it a unique id like "assam_new_scheme"
//   3. Update name, benefit, docs, match() and save.
//   No other file needs to change.
// ─────────────────────────────────────────────────────────────────────────────

export const ASSAM_SCHEMES = [

  {
    id: "assam_orunodoi",
    icon: "👩", color: "#EA580C", scope: "state", state: "Assam",
    ministry: { en: "Assam Finance Dept.", hi: "असम वित्त विभाग" },
    name:    { en: "Orunodoi Scheme (Assam)",                        hi: "ओरुनोदोई योजना (असम)" },
    benefit: { en: "₹1,250/month direct cash to women of low-income families", hi: "कम आय वाली महिलाओं को ₹1,250/माह सीधे बैंक में" },
    tag:     { en: "Women", hi: "महिला" },
    annual: 15000,
    apply:   { en: "assam.gov.in/scheme-page/154", hi: "assam.gov.in/scheme-page/154" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Ration Card","Bank Account (women's name)","Income Certificate"],
               hi: ["आधार कार्ड","राशन कार्ड","बैंक खाता (महिला के नाम)","आय प्रमाण पत्र"] },
    match: (a) => a.state === "Assam" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "assam_atal_amrit",
    icon: "🏥", color: "#0369A1", scope: "state", state: "Assam",
    ministry: { en: "Assam Health & Family Welfare Dept.", hi: "असम स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "Atal Amrit Abhiyan (Assam)",                     hi: "अटल अमृत अभियान (असम)" },
    benefit: { en: "₹2 Lakh/year cashless treatment for 5 critical illness groups", hi: "5 गंभीर रोग समूहों के लिए ₹2 लाख/वर्ष कैशलेस इलाज" },
    tag:     { en: "Health", hi: "स्वास्थ्य" },
    annual: 200000,
    apply:   { en: "atalamritabhiyan.assam.gov.in", hi: "atalamritabhiyan.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Ration Card (BPL/APBPL)","Income Certificate","Residence Proof"],
               hi: ["आधार कार्ड","राशन कार्ड (BPL/APBPL)","आय प्रमाण पत्र","निवास प्रमाण"] },
    match: (a) => a.state === "Assam" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "assam_nijut_moina",
    icon: "📚", color: "#BE185D", scope: "state", state: "Assam",
    ministry: { en: "Assam Education Dept.", hi: "असम शिक्षा विभाग" },
    name:    { en: "Mukhyamantri Nijut Moina (Assam)",               hi: "मुख्यमंत्री निजुत मोइना (असम)" },
    benefit: { en: "₹1,000–₹2,500/month stipend for girl students (Class 11 to PG) to prevent child marriage", hi: "बाल विवाह रोकने के लिए छात्राओं को ₹1,000–₹2,500/माह वजीफा" },
    tag:     { en: "Girl Student", hi: "छात्रा" },
    annual: 12000,
    apply:   { en: "sebaonline.org", hi: "sebaonline.org" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","School / College Enrollment Certificate","Bank Account (girl's name)","Birth Certificate"],
               hi: ["आधार कार्ड","स्कूल/कॉलेज नामांकन प्रमाण","बैंक खाता (छात्रा के नाम)","जन्म प्रमाण पत्र"] },
    match: (a) => a.state === "Assam" && a.who === "student",
  },

  {
    id: "assam_pragyan_bharati",
    icon: "🛵", color: "#7C3AED", scope: "state", state: "Assam",
    ministry: { en: "Assam Education Dept.", hi: "असम शिक्षा विभाग" },
    name:    { en: "Pragyan Bharati Scheme (Assam)",                  hi: "प्रज्ञान भारती योजना (असम)" },
    benefit: { en: "Free scooty for girls scoring 75%+ in HSLC/HS · Free bicycle for other meritorious students", hi: "HSLC/HS में 75%+ लाने वाली छात्राओं को मुफ्त स्कूटी · अन्य को साइकिल" },
    tag:     { en: "Student / Girl", hi: "छात्रा" },
    annual: 60000,
    apply:   { en: "sebaonline.org", hi: "sebaonline.org" }, applyType: "online", // ℹ️ same portal as Nijut Moina & Anundoram Award
    docs:    { en: ["Aadhaar Card","HSLC / HS Marksheet (75%+)","School Certificate","Bank Account"],
               hi: ["आधार कार्ड","HSLC/HS अंकसूची (75%+)","स्कूल प्रमाण पत्र","बैंक खाता"] },
    match: (a) => a.state === "Assam" && a.who === "student",
  },

  {
    id: "assam_anundoram",
    icon: "💻", color: "#1D4ED8", scope: "state", state: "Assam",
    ministry: { en: "Assam Education Dept. (SEBA)", hi: "असम शिक्षा विभाग (SEBA)" },
    name:    { en: "Anundoram Borooah Award (Assam)",                 hi: "आनंदराम बरुआ पुरस्कार (असम)" },
    benefit: { en: "₹1 Lakh cash + free laptop for students scoring Distinction in HSLC", hi: "HSLC में डिस्टिंक्शन पाने पर ₹1 लाख नकद + मुफ्त लैपटॉप" },
    tag:     { en: "Student / Merit", hi: "छात्र / मेधावी" },
    annual: 100000,
    apply:   { en: "sebaonline.org", hi: "sebaonline.org" }, applyType: "online", // ℹ️ same portal as Nijut Moina & Pragyan Bharati
    docs:    { en: ["Aadhaar Card","HSLC Marksheet (Distinction)","School Certificate","Bank Account"],
               hi: ["आधार कार्ड","HSLC अंकसूची (डिस्टिंक्शन)","स्कूल प्रमाण पत्र","बैंक खाता"] },
    match: (a) => a.state === "Assam" && a.who === "student",
  },

  {
    id: "assam_krishi_sajuli",
    icon: "🚜", color: "#15803D", scope: "state", state: "Assam",
    ministry: { en: "Assam Agriculture Dept.", hi: "असम कृषि विभाग" },
    name:    { en: "Mukhyamantri Krishi Sa-Sajuli Yojana (Assam)",   hi: "मुख्यमंत्री कृषि सा-साजुली योजना (असम)" },
    benefit: { en: "Free farm equipment kit worth ₹5,000 to small & marginal farmers", hi: "छोटे और सीमांत किसानों को ₹5,000 के मुफ्त कृषि उपकरण" },
    tag:     { en: "Farmer", hi: "किसान" },
    annual: 5000,
    apply:   { en: "diragri.assam.gov.in", hi: "diragri.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Land Records / Patta","Bank Passbook","Farmer Registration Certificate"],
               hi: ["आधार कार्ड","जमीन के कागज़/पट्टा","बैंक पासबुक","किसान पंजीकरण प्रमाण पत्र"] },
    match: (a) => a.state === "Assam" && a.who === "farmer",
  },

  {
    id: "assam_swanirbhar_naari",
    icon: "💼", color: "#D97706", scope: "state", state: "Assam",
    ministry: { en: "Assam Women & Child Dev. Dept.", hi: "असम महिला एवं बाल विकास विभाग" },
    name:    { en: "Swanirbhar Naari Scheme (Assam)",                 hi: "स्वनिर्भर नारी योजना (असम)" },
    benefit: { en: "Interest-free loan up to ₹50,000 + training for women's self-employment", hi: "महिला स्वरोजगार के लिए ₹50,000 तक ब्याज मुक्त लोन + प्रशिक्षण" },
    tag:     { en: "Women / Business", hi: "महिला / व्यापार" },
    annual: 0,
    apply:   { en: "dht.assam.gov.in/portlets/swanirbhar-naari", hi: "dht.assam.gov.in/portlets/swanirbhar-naari" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Bank Account","Business Plan / Activity Details","Income Certificate","Residence Proof"],
               hi: ["आधार कार्ड","बैंक खाता","व्यापार योजना/गतिविधि विवरण","आय प्रमाण","निवास प्रमाण"] },
    match: (a) => a.state === "Assam" && a.who === "women",
  },

  {
    id: "assam_amrit_briksha",
    icon: "🌳", color: "#065F46", scope: "state", state: "Assam",
    ministry: { en: "Assam Forest & Environment Dept.", hi: "असम वन एवं पर्यावरण विभाग" },
    name:    { en: "Amrit Briksha Andolan (Assam)",                   hi: "अमृत बृक्ष आंदोलन (असम)" },
    benefit: { en: "₹100/sapling reward for planting & nurturing trees for 3 years", hi: "3 साल तक पेड़ उगाने पर ₹100/पौधा पुरस्कार" },
    tag:     { en: "Environment", hi: "पर्यावरण" },
    annual: 5000,
    apply:   { en: "forest.assam.gov.in", hi: "forest.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Bank Account","Land / Land Use Proof","Sapling Planting Proof"],
               hi: ["आधार कार्ड","बैंक खाता","जमीन उपयोग प्रमाण","पौधारोपण प्रमाण"] },
    match: (a) => a.state === "Assam",
  },

  {
    id: "assam_mukhyamantri_atmanirbhar",
    icon: "🧑‍💻", color: "#4338CA", scope: "state", state: "Assam",
    ministry: { en: "Assam Skill, Employment & Entrepreneurship Dept.", hi: "असम कौशल, रोजगार एवं उद्यमिता विभाग" },
    name:    { en: "Mukhyamantri Atmanirbhar Asom Abhiyan",           hi: "मुख्यमंत्री आत्मनिर्भर असम अभियान" },
    benefit: { en: "₹2 Lakh interest-free loan + free skill training for unemployed youth", hi: "बेरोजगार युवाओं के लिए ₹2 लाख ब्याज मुक्त लोन + मुफ्त कौशल प्रशिक्षण" },
    tag:     { en: "Youth / Business", hi: "युवा / व्यापार" },
    annual: 0,
    apply:   { en: "skill.assam.gov.in", hi: "skill.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Educational Certificate","Bank Account","Business Plan","Domicile Certificate"],
               hi: ["आधार कार्ड","शैक्षणिक प्रमाण","बैंक खाता","व्यापार योजना","अधिवास प्रमाण पत्र"] },
    match: (a) => a.state === "Assam" && ["18to35","35to60"].includes(a.age) && ["below1","1to3"].includes(a.income),
  },

  {
    id: "assam_arundhati_gold",
    icon: "💍", color: "#B45309", scope: "state", state: "Assam",
    ministry: { en: "Assam Revenue & Disaster Management Dept.", hi: "असम राजस्व एवं आपदा प्रबंधन विभाग" },
    name:    { en: "Arundhati Gold Scheme (Assam)",                 hi: "अरुंधती गोल्ड योजना (असम)" },
    benefit: { en: "₹40,000 cash directly in bride's bank account to buy gold at marriage", hi: "विवाह पर दुल्हन के बैंक खाते में सीधे ₹40,000 — सोना खरीदने के लिए" },
    tag:     { en: "Women / Marriage", hi: "महिला / विवाह" },
    annual: 40000,
    apply:   { en: "arundhati.assam.gov.in", hi: "arundhati.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Marriage Certificate (registered under Special Marriage Act)","Bank Account (bride's name)","Income Certificate (family income < ₹5 lakh/year)","Age Proof (bride must be 18+, groom 21+)"],
               hi: ["आधार कार्ड","विवाह प्रमाण पत्र (विशेष विवाह अधिनियम के तहत)","बैंक खाता (दुल्हन के नाम)","आय प्रमाण (पारिवारिक आय ₹5 लाख/वर्ष से कम)","आयु प्रमाण (दुल्हन 18+, दूल्हा 21+)"] },
    match: (a) => a.state === "Assam" && a.who === "women",
  },

  {
    id: "assam_svayem",
    icon: "🏪", color: "#0F766E", scope: "state", state: "Assam",
    ministry: { en: "Assam Industries & Commerce Dept.", hi: "असम उद्योग एवं वाणिज्य विभाग" },
    name:    { en: "SVAYEM Scheme (Assam)",                         hi: "स्वायम योजना (असम)" },
    benefit: { en: "Loan up to ₹2 lakh + seed money ₹50,000 for youth starting businesses in manufacturing, trade or services", hi: "व्यापार शुरू करने के लिए ₹2 लाख तक लोन + ₹50,000 सीड मनी" },
    tag:     { en: "Youth / Business", hi: "युवा / व्यापार" },
    annual: 0,
    apply:   { en: "industriescom.assam.gov.in", hi: "industriescom.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Age Proof (18+ years)","Educational Certificate (min. Class VII pass)","Bank Account","Business Plan","Domicile Certificate"],
               hi: ["आधार कार्ड","आयु प्रमाण (18+ वर्ष)","शैक्षणिक प्रमाण (न्यूनतम कक्षा 7 पास)","बैंक खाता","व्यापार योजना","अधिवास प्रमाण पत्र"] },
    match: (a) => a.state === "Assam" && ["18to35","35to60"].includes(a.age),
  },

  {
    id: "assam_aponar_apon_ghar",
    icon: "🏠", color: "#1D4ED8", scope: "state", state: "Assam",
    ministry: { en: "Assam Finance Dept.", hi: "असम वित्त विभाग" },
    name:    { en: "Aponar Apon Ghar Scheme (Assam)",               hi: "अपनार अपन घर योजना (असम)" },
    benefit: { en: "₹2.5 lakh subsidy on first home loan (for loans above ₹5 lakh from scheduled banks)", hi: "पहले घर के लिए होम लोन पर ₹2.5 लाख सब्सिडी (₹5 लाख से अधिक लोन पर)" },
    tag:     { en: "Housing", hi: "आवास" },
    annual: 0,
    apply:   { en: "finance.assam.gov.in", hi: "finance.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Income Certificate (family income ≤ ₹20 lakh/year)","Bank Loan Sanction Letter","Property Documents","Residence Proof","Declaration of first home purchase"],
               hi: ["आधार कार्ड","आय प्रमाण (पारिवारिक आय ≤ ₹20 लाख/वर्ष)","बैंक लोन स्वीकृति पत्र","संपत्ति दस्तावेज़","निवास प्रमाण","पहले घर की खरीद की घोषणा"] },
    match: (a) => a.state === "Assam" && a.housing === "no",
  },

  {
    id: "assam_kushal_konwar_pension",
    icon: "👴", color: "#6D28D9", scope: "state", state: "Assam",
    ministry: { en: "Assam Social Welfare Dept.", hi: "असम समाज कल्याण विभाग" },
    name:    { en: "Kushal Konwar Briddha Pension (Assam)",         hi: "कुशल कोंवर वृद्धा पेंशन योजना (असम)" },
    benefit: { en: "Monthly old-age pension for senior citizens aged 60+ not covered under any other pension scheme", hi: "60+ वर्ष के वरिष्ठ नागरिकों को मासिक वृद्धा पेंशन जो किसी अन्य पेंशन से वंचित हैं" },
    tag:     { en: "Senior / Pension", hi: "वरिष्ठ / पेंशन" },
    annual: 0,
    apply:   { en: "socialjustice.assam.gov.in", hi: "socialjustice.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Age Proof (60+ years)","Bank Account","BPL / Income Certificate","Residence Proof","Declaration of no other pension"],
               hi: ["आधार कार्ड","आयु प्रमाण (60+ वर्ष)","बैंक खाता","BPL/आय प्रमाण पत्र","निवास प्रमाण","किसी अन्य पेंशन न होने की घोषणा"] },
    match: (a) => a.state === "Assam" && a.age === "60plus",
  },

  {
    id: "assam_lakhpati_baideo",
    icon: "💰", color: "#B45309", scope: "state", state: "Assam",
    ministry: { en: "Assam Panchayat & Rural Development Dept.", hi: "असम पंचायत एवं ग्रामीण विकास विभाग" },
    name:    { en: "Lakhpati Baideo Scheme (Assam)",               hi: "लखपति बाइदेउ योजना (असम)" },
    benefit: { en: "₹35,000 financial assistance to women SHG members to start small businesses — targets 40 lakh women", hi: "महिला SHG सदस्यों को छोटा व्यवसाय शुरू करने के लिए ₹35,000 की सहायता — 40 लाख महिलाओं का लक्ष्य" },
    tag:     { en: "Women / SHG", hi: "महिला / स्वयं सहायता समूह" },
    annual: 35000,
    apply:   { en: "asrlms.assam.gov.in", hi: "asrlms.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","SHG Membership Certificate","Bank Account (Aadhaar-linked)","Residence Proof","Passport Photo"],
               hi: ["आधार कार्ड","SHG सदस्यता प्रमाण पत्र","बैंक खाता (आधार लिंक्ड)","निवास प्रमाण","पासपोर्ट फोटो"] },
    match: (a) => a.state === "Assam" && a.who === "women",
  },

  {
    id: "assam_indira_miri_widow",
    icon: "🤲", color: "#6D28D9", scope: "state", state: "Assam",
    ministry: { en: "Assam Panchayat & Rural Development Dept.", hi: "असम पंचायत एवं ग्रामीण विकास विभाग" },
    name:    { en: "Indira Miri Universal Widow Pension (Assam)",  hi: "इंदिरा मिरि सार्वभौमिक विधवा पेंशन (असम)" },
    benefit: { en: "₹25,000 one-time immediate financial assistance to widows (age 45–60) on death of husband", hi: "पति की मृत्यु पर विधवाओं (45–60 वर्ष) को ₹25,000 की एकमुश्त तत्काल सहायता" },
    tag:     { en: "Women / Widow", hi: "महिला / विधवा" },
    annual: 25000,
    apply:   { en: "pnrd.assam.gov.in", hi: "pnrd.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Husband's Death Certificate","Age Proof (45–60 years)","BPL / APL Ration Card","Bank Account","Residence Proof"],
               hi: ["आधार कार्ड","पति का मृत्यु प्रमाण पत्र","आयु प्रमाण (45–60 वर्ष)","BPL/APL राशन कार्ड","बैंक खाता","निवास प्रमाण"] },
    match: (a) => a.state === "Assam" && a.who === "women",
  },

  {
    id: "assam_sarothi",
    icon: "🚀", color: "#0369A1", scope: "state", state: "Assam",
    ministry: { en: "Assam Industries & Commerce Dept.", hi: "असम उद्योग एवं वाणिज्य विभाग" },
    name:    { en: "Sarothi Start-Up Fund (Assam)",                hi: "सारथी स्टार्टअप फंड (असम)" },
    benefit: { en: "Seed capital + working capital funding for first-generation entrepreneurs and innovative startups in Assam", hi: "असम में पहली पीढ़ी के उद्यमियों और स्टार्टअप को सीड कैपिटल + वर्किंग कैपिटल सहायता" },
    tag:     { en: "Startup / Business", hi: "स्टार्टअप / व्यापार" },
    annual: 0,
    apply:   { en: "industriescom.assam.gov.in", hi: "industriescom.assam.gov.in" }, applyType: "online", // ℹ️ same portal as SVAYEM
    docs:    { en: ["Aadhaar Card","Business / Startup Plan","Educational Certificate","Bank Account","Domicile Certificate","No-Defaulter Declaration from Bank"],
               hi: ["आधार कार्ड","व्यापार/स्टार्टअप योजना","शैक्षणिक प्रमाण","बैंक खाता","अधिवास प्रमाण","बैंक डिफॉल्टर न होने की घोषणा"] },
    match: (a) => a.state === "Assam" && ["18to35","35to60"].includes(a.age),
  },

  {
    id: "assam_jibon_prerana",
    icon: "🎓", color: "#0D9488", scope: "state", state: "Assam",
    ministry: { en: "Assam Skill, Employment & Entrepreneurship Dept.", hi: "असम कौशल, रोजगार एवं उद्यमिता विभाग" },
    name:    { en: "Chief Minister's Jibon Prerana Scheme (Assam)",      hi: "मुख्यमंत्री जीबन प्रेरणा योजना (असम)" },
    benefit: { en: "₹2,500/month for 12 months for fresh graduates (2025 pass-outs) of govt. institutions to support job search & competitive exam prep; Research Scholars get ₹25,000 one-time grant", hi: "सरकारी संस्थानों के नए स्नातकों को नौकरी खोज व परीक्षा तैयारी के लिए 12 माह तक ₹2,500/माह; शोधकर्ताओं को ₹25,000 एकमुश्त" },
    tag:     { en: "Youth / Graduate", hi: "युवा / स्नातक" },
    annual: 30000,
    apply:   { en: "dids.assam.gov.in", hi: "dids.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Graduation Certificate (Govt. institution, 2025 pass-out)","Bank Account (Aadhaar-linked)","Domicile / Residence Certificate","Unemployment Declaration","Mobile Number for OTP"],
               hi: ["आधार कार्ड","स्नातक प्रमाण पत्र (सरकारी संस्थान, 2025 पास-आउट)","बैंक खाता (आधार लिंक्ड)","अधिवास/निवास प्रमाण","बेरोजगारी घोषणा","OTP के लिए मोबाइल नंबर"] },
    match: (a) => a.state === "Assam" && a.who === "student" && ["18to35"].includes(a.age),
  },

  {
    id: "assam_abhinandan_loan",
    icon: "📖", color: "#2563EB", scope: "state", state: "Assam",
    ministry: { en: "Assam Finance Dept.", hi: "असम वित्त विभाग" },
    name:    { en: "Abhinandan Education Loan Subsidy Scheme 2.0 (Assam)", hi: "अभिनंदन शिक्षा ऋण सब्सिडी योजना 2.0 (असम)" },
    benefit: { en: "₹50,000 one-time subsidy on education loans of ₹2 lakh+ taken from scheduled commercial or rural banks between 01-Apr-2020 and 31-Mar-2024; only after repaying 25% of loan", hi: "₹2 लाख+ के शिक्षा ऋण पर ₹50,000 एकमुश्त सब्सिडी (25% चुकाने के बाद)" },
    tag:     { en: "Student / Education Loan", hi: "छात्र / शिक्षा ऋण" },
    annual: 50000,
    apply:   { en: "dids.assam.gov.in", hi: "dids.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Bank Loan Sanction Letter (₹2 lakh+, from Scheduled Bank)","Loan Repayment Proof (25% repaid)","Admission / Enrollment Certificate (Higher Education)","Bank Account","Domicile Certificate"],
               hi: ["आधार कार्ड","बैंक ऋण स्वीकृति पत्र (₹2 लाख+, अनुसूचित बैंक)","ऋण पुनर्भुगतान प्रमाण (25% चुकाया)","प्रवेश/नामांकन प्रमाण पत्र (उच्च शिक्षा)","बैंक खाता","अधिवास प्रमाण पत्र"] },
    match: (a) => a.state === "Assam" && a.who === "student",
  },

  {
    id: "assam_silpi_pension",
    icon: "🎭", color: "#7C2D92", scope: "state", state: "Assam",
    ministry: { en: "Directorate of Cultural Affairs, Assam", hi: "सांस्कृतिक मामलों का निदेशालय, असम" },
    name:    { en: "Silpi Pension Scheme (Assam)",                        hi: "शिल्पी पेंशन योजना (असम)" },
    benefit: { en: "Monthly pension for artistes aged 60+ who contributed to Assam's art & culture (Music, Dance, Fine Arts, Theatre, Film, etc.) · One-time Barxik Silpi Sanman grant of ₹50,000 · ₹50,000 one-time assistance to families of deceased artistes", hi: "असम की कला-संस्कृति में योगदान देने वाले 60+ वर्षीय कलाकारों को मासिक पेंशन · बार्षिक शिल्पी सम्मान ₹50,000 · दिवंगत कलाकार के परिवार को ₹50,000 एकमुश्त" },
    tag:     { en: "Artist / Senior", hi: "कलाकार / वरिष्ठ" },
    annual: 0,
    apply:   { en: "culturalaffairs.assam.gov.in", hi: "culturalaffairs.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","PAN Card","Age Proof (60+ years)","Recognition / Award Proof Certificate (field of art/culture)","Bank Account","Passport Photo","Identity Proof (Voter ID / Passport / Driving License)"],
               hi: ["आधार कार्ड","PAN कार्ड","आयु प्रमाण (60+ वर्ष)","कला/संस्कृति क्षेत्र में मान्यता/पुरस्कार प्रमाण पत्र","बैंक खाता","पासपोर्ट फोटो","पहचान प्रमाण (मतदाता ID/पासपोर्ट/ड्राइविंग लाइसेंस)"] },
    match: (a) => a.state === "Assam" && a.age === "60plus",
  },

  {
    id: "assam_shishu_seva",
    icon: "👶", color: "#DC2626", scope: "state", state: "Assam",
    ministry: { en: "Assam Social Welfare & Education Dept.", hi: "असम समाज कल्याण एवं शिक्षा विभाग" },
    name:    { en: "Mukhyamantri Shishu Seva Scheme (Assam)",            hi: "मुख्यमंत्री शिशु सेवा योजना (असम)" },
    benefit: { en: "₹3,500/month till age 24 for children orphaned due to COVID-19 · ₹7,81,200 fixed deposit in child's name (principal released at age 24) · Free residential schooling for orphan girls with no guardian · ₹50,000 marriage assistance for orphan girls", hi: "COVID-19 से अनाथ बच्चों को 24 वर्ष तक ₹3,500/माह · ₹7,81,200 FD बच्चे के नाम · अनाथ छात्राओं को मुफ्त आवासीय शिक्षा · विवाह पर ₹50,000 सहायता" },
    tag:     { en: "Child / COVID Orphan", hi: "बच्चा / COVID अनाथ" },
    annual: 42000,
    apply:   { en: "cmcovidsupport.assam.gov.in", hi: "cmcovidsupport.assam.gov.in" }, applyType: "online",
    closed:  true, // ⚠️ Portal closed since 2022 — no new applications accepted
    docs:    { en: ["Aadhaar Card (child)","Death Certificate of Parent(s) — COVID-19 certified","Domicile Certificate (Assam)","Guardian's ID & Bank Account","School Enrollment Proof","Birth Certificate (child)"],
               hi: ["आधार कार्ड (बच्चे का)","माता/पिता का मृत्यु प्रमाण पत्र — COVID-19 प्रमाणित","अधिवास प्रमाण पत्र (असम)","अभिभावक का पहचान व बैंक खाता","स्कूल नामांकन प्रमाण","जन्म प्रमाण पत्र (बच्चे का)"] },
    match: (a) => a.state === "Assam",
  },

  {
    id: "assam_covid_widow",
    icon: "🤍", color: "#475569", scope: "state", state: "Assam",
    ministry: { en: "Chief Minister's Secretariat, Assam", hi: "मुख्यमंत्री सचिवालय, असम" },
    name:    { en: "CM's Covid-19 Widow Support Scheme (Assam)",         hi: "मुख्यमंत्री कोविड-19 विधवा सहायता योजना (असम)" },
    benefit: { en: "₹2.5 lakh one-time financial assistance to widows of COVID-19 victims from low-income families (annual family income ≤ ₹5 lakh); widows already under Orunodoi or Widow Pension are also eligible", hi: "COVID-19 से पति खोने वाली विधवाओं को एकमुश्त ₹2.5 लाख (पारिवारिक आय ≤ ₹5 लाख); ओरुनोदोई या विधवा पेंशन लाभार्थी भी पात्र" },
    tag:     { en: "Women / COVID Widow", hi: "महिला / COVID विधवा" },
    annual: 250000,
    apply:   { en: "cmcovidsupport.assam.gov.in", hi: "cmcovidsupport.assam.gov.in" }, applyType: "online",
    closed:  true, // ⚠️ Portal closed since 2022 — no new applications accepted
    docs:    { en: ["Aadhaar Card","Husband's Death Certificate (COVID-19, certified by State Level COVID Death Audit Board)","Income Certificate (family income ≤ ₹5 lakh/year)","Bank Account (widow's name)","Residence Proof","Ration Card"],
               hi: ["आधार कार्ड","पति का मृत्यु प्रमाण पत्र (COVID-19, राज्य स्तरीय बोर्ड प्रमाणित)","आय प्रमाण पत्र (पारिवारिक आय ≤ ₹5 लाख/वर्ष)","बैंक खाता (विधवा के नाम)","निवास प्रमाण","राशन कार्ड"] },
    match: (a) => a.state === "Assam" && a.who === "women" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "assam_mmua",
    icon: "🏭", color: "#BE185D", scope: "state", state: "Assam",
    ministry: { en: "Assam Panchayat & Rural Development Dept. (ASRLM)", hi: "असम पंचायत एवं ग्रामीण विकास विभाग (ASRLM)" },
    name:    { en: "Mukhyamantri Mahila Udyamita Abhiyan (Assam)",        hi: "मुख्यमंत्री महिला उद्यमिता अभियान (असम)" },
    benefit: { en: "₹10,000 seed capital (Phase 1) + ₹25,000 loan (Phase 2) + further support up to ₹85,000 total for women SHG members to become rural micro-entrepreneurs (Lakhpati Baideo)", hi: "महिला SHG सदस्यों को चरणबद्ध रूप से ₹10,000 सीड कैपिटल + ₹25,000 लोन + कुल ₹85,000 तक सहायता — ग्रामीण सूक्ष्म उद्यमी (लखपति बाइदेउ) बनाने के लिए" },
    tag:     { en: "Women / SHG / Entrepreneurship", hi: "महिला / SHG / उद्यमिता" },
    annual: 85000,
    apply:   { en: "pnrd.assam.gov.in", hi: "pnrd.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","SHG Membership Certificate (active ASRLM SHG)","Aadhaar-linked Savings Bank Account","Business Plan (from 145 Govt.-approved plans)","Residence Proof","Passport Photo","No-default declaration (SHG/bank)"],
               hi: ["आधार कार्ड","SHG सदस्यता प्रमाण पत्र (सक्रिय ASRLM SHG)","आधार-लिंक्ड बचत बैंक खाता","व्यापार योजना (145 सरकार-अनुमोदित योजनाओं में से)","निवास प्रमाण","पासपोर्ट फोटो","बैंक/SHG डिफॉल्टर न होने की घोषणा"] },
    match: (a) => a.state === "Assam" && a.who === "women",
  },

  {
    id: "assam_mmlsay",
    icon: "🏥", color: "#0F766E", scope: "state", state: "Assam",
    ministry: { en: "Assam Health & Family Welfare Dept.", hi: "असम स्वास्थ्य एवं परिवार कल्याण विभाग" },
    name:    { en: "Mukhya Mantri Lok Sevak Arogya Yojana (Assam)",       hi: "मुख्यमंत्री लोक सेवक आरोग्य योजना (असम)" },
    benefit: { en: "₹5 lakh/year cashless medical treatment at empanelled private hospitals for Assam State Govt. employees, pensioners and their dependents — replaces old reimbursement system", hi: "असम सरकार के कर्मचारियों, पेंशनरों एवं परिवार के लिए ₹5 लाख/वर्ष कैशलेस इलाज — पुरानी प्रतिपूर्ति प्रणाली की जगह" },
    tag:     { en: "Health / Govt Employee", hi: "स्वास्थ्य / सरकारी कर्मचारी" },
    annual: 500000,
    apply:   { en: "mmlsay.assam.gov.in", hi: "mmlsay.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Employee / Pensioner ID","Service Book / PPO (Pension Payment Order)","ABHA Health Card (linked)","Dependent Family Member Proof","Bank Account"],
               hi: ["आधार कार्ड","कर्मचारी/पेंशनर पहचान पत्र","सर्विस बुक/PPO","ABHA हेल्थ कार्ड (लिंक्ड)","आश्रित परिवार सदस्य प्रमाण","बैंक खाता"] },
    match: (a) => a.state === "Assam",
  },

  {
    id: "assam_basundhara",
    icon: "🗺️", color: "#15803D", scope: "state", state: "Assam",
    ministry: { en: "Assam Revenue & Disaster Management Dept.", hi: "असम राजस्व एवं आपदा प्रबंधन विभाग" },
    name:    { en: "Mission Basundhara 3.0 (Assam)",                      hi: "मिशन बसुंधरा 3.0 (असम)" },
    benefit: { en: "Free online land-record services — land mutation, Annual-to-Periodic Patta conversion, homestead land allotment for landless indigenous families (up to 1 bigha), correction of land records, settlement of Bhoodan/Gramdan land, and more", hi: "मुफ्त ऑनलाइन भूमि सेवाएँ — भूमि उत्परिवर्तन, वार्षिक से आवधिक पट्टा रूपांतरण, भूमिहीन परिवारों को 1 बीघा तक गृहस्थल भूमि, जमीन रिकॉर्ड सुधार आदि" },
    tag:     { en: "Farmer / Land", hi: "किसान / भूमि" },
    annual: 0,
    apply:   { en: "basundhara.assam.gov.in", hi: "basundhara.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card / PAN Card (for login)","Existing Land Documents / Patta","Revenue Receipt","Caste Certificate (SC/ST applicants)","Residence Proof","Relevant deed / ownership documents (varies by service)"],
               hi: ["आधार कार्ड/PAN कार्ड (लॉगिन के लिए)","मौजूदा भूमि दस्तावेज़/पट्टा","राजस्व रसीद","जाति प्रमाण पत्र (SC/ST)","निवास प्रमाण","संबंधित विलेख/स्वामित्व दस्तावेज़ (सेवा अनुसार)"] },
    match: (a) => a.state === "Assam" && (a.who === "farmer" || a.housing === "no"),
  },

  {
    id: "assam_arohan",
    icon: "🌟", color: "#D97706", scope: "state", state: "Assam",
    ministry: { en: "Assam Education Dept. / Samagra Shiksha Assam", hi: "असम शिक्षा विभाग / समग्र शिक्षा असम" },
    name:    { en: "Arohan Mentor-Mentee Scheme (Assam)",                 hi: "आरोहण मेंटर-मेंटी योजना (असम)" },
    benefit: { en: "₹1,000 book grant (DBT) + free Samsung Tablet for meritorious govt-school students of Classes XI–XII + career mentoring sessions with IAS/IPS officers, professionals & entrepreneurs", hi: "मेधावी सरकारी स्कूल छात्रों (कक्षा XI–XII) को ₹1,000 किताब अनुदान (DBT) + मुफ्त सैमसंग टैबलेट + IAS/IPS अधिकारियों व पेशेवरों के साथ करियर मेंटरिंग" },
    tag:     { en: "Student / Career", hi: "छात्र / करियर" },
    annual: 1000,
    apply:   { en: "arohan-ssa.assam.gov.in", hi: "arohan-ssa.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Class X Marksheet (First Division / merit)","School Enrollment Certificate (Govt. school, Class XI/XII)","Bank Account (Aadhaar-linked, for DBT)","Passport Photo"],
               hi: ["आधार कार्ड","कक्षा X अंकसूची (प्रथम श्रेणी/मेधावी)","स्कूल नामांकन प्रमाण पत्र (सरकारी स्कूल, कक्षा XI/XII)","बैंक खाता (आधार-लिंक्ड, DBT के लिए)","पासपोर्ट फोटो"] },
    match: (a) => a.state === "Assam" && a.who === "student",
  },

  {
    id: "assam_apun_bahan",
    icon: "🚗", color: "#1D4ED8", scope: "state", state: "Assam",
    ministry: { en: "Assam Finance Dept.", hi: "असम वित्त विभाग" },
    name:    { en: "Apun Bahan Scheme (Assam)",                              hi: "अपुन बाहन योजना (असम)" },
    benefit: { en: "Interest subvention on vehicle loans up to ₹15 lakh for permanent Assam State Govt. employees — 2% interest for petrol/diesel vehicles (male), 3% for electric vehicles or any vehicle (female/disabled employees); 2-wheeler & 4-wheeler only; repayment up to 7 years", hi: "असम राज्य सरकार के स्थायी कर्मचारियों को ₹15 लाख तक के वाहन ऋण पर ब्याज सब्सिडी — पेट्रोल/डीजल वाहन पर 2%, इलेक्ट्रिक/महिला/दिव्यांग कर्मचारी के लिए 3%; 2-व्हीलर और 4-व्हीलर केवल; 7 वर्ष तक पुनर्भुगतान" },
    tag:     { en: "Govt Employee / Vehicle Loan", hi: "सरकारी कर्मचारी / वाहन ऋण" },
    annual: 0,
    apply:   { en: "finance.assam.gov.in", hi: "finance.assam.gov.in" }, applyType: "offline", // ⚠️ offline — apply through employer/DDO to Finance Dept.
    docs:    { en: ["Employee ID / Service Book","Salary Certificate (DDO certified)","Statement of Dues & Drawing Salary","Aadhaar Card","Bank Account (salary account)","Vehicle Quotation / Pro-forma Invoice","Age Proof (21–53 years)","Domicile / Residence Proof"],
               hi: ["कर्मचारी पहचान पत्र/सर्विस बुक","वेतन प्रमाण पत्र (DDO प्रमाणित)","बकाया और वेतन निकासी विवरण","आधार कार्ड","बैंक खाता (वेतन खाता)","वाहन कोटेशन/प्रो-फॉर्मा इनवॉइस","आयु प्रमाण (21–53 वर्ष)","अधिवास/निवास प्रमाण"] },
    match: (a) => a.state === "Assam",
  },

  {
    id: "assam_apun_ghar",
    icon: "🏡", color: "#0369A1", scope: "state", state: "Assam",
    ministry: { en: "Assam Finance Dept.", hi: "असम वित्त विभाग" },
    name:    { en: "Apun Ghar Scheme (Assam)",                               hi: "अपुन घर योजना (असम)" },
    benefit: { en: "3.5% interest subvention on home loans up to ₹15 lakh via SBI for regular Assam State Govt. employees — effective rate 5.00% (women) / 5.05% (men) after subsidy; repayment up to 20 years", hi: "असम राज्य के नियमित सरकारी कर्मचारियों को SBI के माध्यम से ₹15 लाख तक के गृह ऋण पर 3.5% ब्याज सब्सिडी — सब्सिडी के बाद प्रभावी दर 5.00% (महिला)/5.05% (पुरुष); 20 वर्ष तक पुनर्भुगतान" },
    tag:     { en: "Govt Employee / Housing Loan", hi: "सरकारी कर्मचारी / गृह ऋण" },
    annual: 0,
    apply:   { en: "finance.assam.gov.in", hi: "finance.assam.gov.in" }, applyType: "offline", // ⚠️ offline — apply through SBI + employer NOC
    docs:    { en: ["Employee ID / Service Book","Salary Certificate (DDO certified)","Aadhaar Card","Bank Account (salary account at SBI)","Property / Land Documents","Approved Building Plan","Income Certificate","No Objection Certificate (employer)","Age & Domicile Proof"],
               hi: ["कर्मचारी पहचान पत्र/सर्विस बुक","वेतन प्रमाण पत्र (DDO प्रमाणित)","आधार कार्ड","बैंक खाता (SBI वेतन खाता)","संपत्ति/भूमि दस्तावेज़","अनुमोदित भवन योजना","आय प्रमाण पत्र","नियोक्ता से अनापत्ति प्रमाण पत्र","आयु व अधिवास प्रमाण"] },
    match: (a) => a.state === "Assam" && a.housing === "no",
  },

  {
    id: "assam_bigyan_pratibha",
    icon: "🔬", color: "#0D9488", scope: "state", state: "Assam",
    ministry: { en: "Assam Science, Technology & Environment Council (ASTEC)", hi: "असम विज्ञान, प्रौद्योगिकी एवं पर्यावरण परिषद (ASTEC)" },
    name:    { en: "CM's Bigyan Pratibha Sandhan (Assam)",                   hi: "मुख्यमंत्री बिगयान प्रतिभा संधान (असम)" },
    benefit: { en: "Top 100 Class XI Science students (50 girls) get a one-week fellowship at India's premier scientific institutions; top 5 get international exposure at world-famous research centres · Mentoring by leading scientists", hi: "शीर्ष 100 कक्षा XI विज्ञान छात्रों (50 छात्राओं) को देश के प्रमुख वैज्ञानिक संस्थानों में एक-सप्ताह की फेलोशिप; शीर्ष 5 को विश्वस्तरीय अनुसंधान केंद्रों में अंतर्राष्ट्रीय दौरा · प्रमुख वैज्ञानिकों से मेंटरिंग" },
    tag:     { en: "Student / Science", hi: "छात्र / विज्ञान" },
    annual: 0,
    apply:   { en: "astec.assam.gov.in", hi: "astec.assam.gov.in" }, applyType: "online",
    docs:    { en: ["Aadhaar Card","Class X Marksheet (minimum 75% marks)","Class XI Enrollment Certificate (Science stream — Maths/Physics/Chemistry/Biology/Statistics/CS)","School Certificate (Govt. recognised institution in Assam)","Passport Photo","Mobile Number for OTP"],
               hi: ["आधार कार्ड","कक्षा X अंकसूची (न्यूनतम 75% अंक)","कक्षा XI नामांकन प्रमाण पत्र (विज्ञान धारा)","स्कूल प्रमाण पत्र (असम में सरकार-मान्यता प्राप्त)","पासपोर्ट फोटो","OTP के लिए मोबाइल नंबर"] },
    match: (a) => a.state === "Assam" && a.who === "student",
  },

  {
    id: "assam_chah_bagicha",
    icon: "🍵", color: "#15803D", scope: "state", state: "Assam",
    ministry: { en: "Assam Labour Welfare Dept. (Tea Tribe)", hi: "असम श्रम कल्याण विभाग (चाय जनजाति)" },
    name:    { en: "Chah Bagicha Dhan Puraskar Mela (Assam)",               hi: "चाह बागिचा धन पुरस्कार मेला (असम)" },
    benefit: { en: "₹3,000 direct cash to bank accounts of tea garden workers (BPL women included); promotes financial inclusion and cashless banking among tea garden communities; ~7.5 lakh workers covered", hi: "चाय बागान श्रमिकों के बैंक खातों में सीधे ₹3,000 नकद (BPL महिलाएं शामिल); चाय बागान समुदाय में वित्तीय समावेशन; ~7.5 लाख श्रमिक लाभान्वित" },
    tag:     { en: "Tea Worker / Labour", hi: "चाय श्रमिक / मजदूर" },
    annual: 3000,
    apply:   { en: "labour.assam.gov.in", hi: "labour.assam.gov.in" }, applyType: "offline", // ⚠️ offline — apply via tea garden manager / Labour Welfare Dept.
    docs:    { en: ["Aadhaar Card","Tea Garden Employment Card / Identity Proof","Bank Account (Aadhaar-linked)","BPL / Ration Card (for BPL category)","Residence Proof (tea garden area)"],
               hi: ["आधार कार्ड","चाय बागान रोजगार कार्ड/पहचान प्रमाण","बैंक खाता (आधार लिंक्ड)","BPL/राशन कार्ड (BPL श्रेणी के लिए)","निवास प्रमाण (चाय बागान क्षेत्र)"] },
    match: (a) => a.state === "Assam" && ["below1","1to3"].includes(a.income),
  },

  {
    id: "assam_jibika_sakhi",
    icon: "🛵", color: "#BE185D", scope: "state", state: "Assam",
    ministry: { en: "Assam State Rural Livelihood Mission (ASRLM)", hi: "असम राज्य ग्रामीण आजीविका मिशन (ASRLM)" },
    name:    { en: "Jibika Sakhi Express Scheme (Assam)",                    hi: "जीविका सखी एक्सप्रेस योजना (असम)" },
    benefit: { en: "Free scooter to women SHG community cadres (Krishi Sakhi, Pashu Sakhi, Bima Sakhi, Jibika Sakhi etc.) to travel rural areas and support self-help groups; over 10,900 scooters distributed so far", hi: "महिला SHG सामुदायिक कार्यकर्ताओं (कृषि सखी, पशु सखी, बीमा सखी, जीविका सखी आदि) को ग्रामीण क्षेत्रों में जाने व SHG सहयोग के लिए मुफ्त स्कूटर; अब तक 10,900+ स्कूटर वितरित" },
    tag:     { en: "Women / SHG / Rural", hi: "महिला / SHG / ग्रामीण" },
    annual: 60000,
    apply:   { en: "asrlms.assam.gov.in", hi: "asrlms.assam.gov.in" }, applyType: "offline", // ⚠️ offline — apply via ASRLM block office; ℹ️ same portal as Lakhpati Baideo
    docs:    { en: ["Aadhaar Card","ASRLM Community Cadre Certificate (Krishi/Pashu/Bima/Jibika Sakhi)","SHG Membership Certificate","Bank Account (Aadhaar-linked)","Residence Proof","Passport Photo","Driving Licence (2-wheeler, or willingness to obtain)"],
               hi: ["आधार कार्ड","ASRLM सामुदायिक कार्यकर्ता प्रमाण पत्र (कृषि/पशु/बीमा/जीविका सखी)","SHG सदस्यता प्रमाण पत्र","बैंक खाता (आधार लिंक्ड)","निवास प्रमाण","पासपोर्ट फोटो","ड्राइविंग लाइसेंस (2-व्हीलर)"] },
    match: (a) => a.state === "Assam" && a.who === "women",
  },

  // ADD MORE ASSAM SCHEMES ABOVE THIS LINE ↓
  // {
  //   id: "assam_new_scheme",
  //   icon: "🆕", color: "#123456", scope: "state", state: "Assam",
  //   ministry: { en: "Dept. Name", hi: "विभाग का नाम" },
  //   name:    { en: "Scheme Name", hi: "योजना का नाम" },
  //   benefit: { en: "Benefit details", hi: "लाभ विवरण" },
  //   tag:     { en: "Tag", hi: "टैग" },
  //   annual: 0,
  //   apply:   { en: "website.gov.in", hi: "website.gov.in" }, applyType: "online",
  //   docs:    { en: ["Aadhaar Card"], hi: ["आधार कार्ड"] },
  //   match: (a) => a.state === "Assam",
  // },

];
